import { StyleSheet } from "react-native";
import { n } from "./n"

const size = [n(0), n(4), n(8), n(16), n(24), n(32), n(36), n(48)];

export const styles = StyleSheet.create({
    /* space*/
    pl0: { paddingLeft: size[0] },
    pl1: { paddingLeft: size[1] },
    pl2: { paddingLeft: size[2] },
    pl3: { paddingLeft: size[3] },
    pl4: { paddingLeft: size[4] },
    pl5: { paddingLeft: size[5] },
    pl6: { paddingLeft: size[6] },
    pl7: { paddingLeft: size[7] },
    pr0: { paddingRight: size[0] },
    pr1: { paddingRight: size[1] },
    pr2: { paddingRight: size[2] },
    pr3: { paddingRight: size[3] },
    pr4: { paddingRight: size[4] },
    pr5: { paddingRight: size[5] },
    pr6: { paddingRight: size[6] },
    pr7: { paddingRight: size[7] },
    pt0: { paddingTop: size[0] },
    pt1: { paddingTop: size[1] },
    pt2: { paddingTop: size[2] },
    pt3: { paddingTop: size[3] },
    pt4: { paddingTop: size[4] },
    pt5: { paddingTop: size[5] },
    pt6: { paddingTop: size[6] },
    pt7: { paddingTop: size[7] },
    pb0: { paddingBottom: size[0] },
    pb1: { paddingBottom: size[1] },
    pb2: { paddingBottom: size[2] },
    pb3: { paddingBottom: size[3] },
    pb4: { paddingBottom: size[4] },
    pb5: { paddingBottom: size[5] },
    pb6: { paddingBottom: size[6] },
    pb7: { paddingBottom: size[7] },
    pa0: { padding: size[0] },
    pa1: { padding: size[1] },
    pa2: { padding: size[2] },
    pa3: { padding: size[3] },
    pa4: { padding: size[4] },
    pa5: { padding: size[5] },
    pa6: { padding: size[6] },
    pa7: { padding: size[7] },
    py0: { paddingVertical: size[0] },
    py1: { paddingVertical: size[1] },
    py2: { paddingVertical: size[2] },
    py3: { paddingVertical: size[3] },
    py4: { paddingVertical: size[4] },
    py5: { paddingVertical: size[5] },
    py6: { paddingVertical: size[6] },
    py7: { paddingVertical: size[7] },
    px0: { paddingHorizontal: size[0] },
    px1: { paddingHorizontal: size[1] },
    px2: { paddingHorizontal: size[2] },
    px3: { paddingHorizontal: size[3] },
    px4: { paddingHorizontal: size[4] },
    px5: { paddingHorizontal: size[5] },
    px6: { paddingHorizontal: size[6] },
    px7: { paddingHorizontal: size[7] },
    ml0: { marginLeft: size[0] },
    ml1: { marginLeft: size[1] },
    ml2: { marginLeft: size[2] },
    ml3: { marginLeft: size[3] },
    ml4: { marginLeft: size[4] },
    ml5: { marginLeft: size[5] },
    ml6: { marginLeft: size[6] },
    ml7: { marginLeft: size[7] },
    mr0: { marginRight: size[0] },
    mr1: { marginRight: size[1] },
    mr2: { marginRight: size[2] },
    mr3: { marginRight: size[3] },
    mr4: { marginRight: size[4] },
    mr5: { marginRight: size[5] },
    mr6: { marginRight: size[6] },
    mr7: { marginRight: size[7] },
    mt0: { marginTop: size[0] },
    mt1: { marginTop: size[1] },
    mt2: { marginTop: size[2] },
    mt3: { marginTop: size[3] },
    mt4: { marginTop: size[4] },
    mt5: { marginTop: size[5] },
    mt6: { marginTop: size[6] },
    mt7: { marginTop: size[7] },
    mb0: { marginBottom: size[0] },
    mb1: { marginBottom: size[1] },
    mb2: { marginBottom: size[2] },
    mb3: { marginBottom: size[3] },
    mb4: { marginBottom: size[4] },
    mb5: { marginBottom: size[5] },
    mb6: { marginBottom: size[6] },
    mb7: { marginBottom: size[7] },
    ma0: { margin: size[0] },
    ma1: { margin: size[1] },
    ma2: { margin: size[2] },
    ma3: { margin: size[3] },
    ma4: { margin: size[4] },
    ma5: { margin: size[5] },
    ma6: { margin: size[6] },
    ma7: { margin: size[7] },
    my0: { marginVertical: size[0] },
    my1: { marginVertical: size[1] },
    my2: { marginVertical: size[2] },
    my3: { marginVertical: size[3] },
    my4: { marginVertical: size[4] },
    my5: { marginVertical: size[5] },
    my6: { marginVertical: size[6] },
    my7: { marginVertical: size[7] },
    mx0: { marginHorizontal: size[0] },
    mx1: { marginHorizontal: size[1] },
    mx2: { marginHorizontal: size[2] },
    mx3: { marginHorizontal: size[3] },
    mx4: { marginHorizontal: size[4] },
    mx5: { marginHorizontal: size[5] },
    mx6: { marginHorizontal: size[6] },
    mx7: { marginHorizontal: size[7] },

    w10: { width: n(320 * 0.1) },
    w20: { width: n(320 * 0.2) },
    w30: { width: n(320 * 0.3) },
    w40: { width: n(320 * 0.4) },
    w50: { width: n(320 * 0.5) },
    w60: { width: n(320 * 0.6) },
    w70: { width: n(320 * 0.7) },
    w80: { width: n(320 * 0.8) },
    w90: { width: n(320 * 0.9) },
    w100: { width: "100%" },

    /* flexBox */
    flex1: { flex: 1 },
    flex2: { flex: 2 },
    flex3: { flex: 3 },
    flex4: { flex: 4 },
    flex5: { flex: 5 },
    flex6: { flex: 6 },
    flex7: { flex: 7 },
    flex8: { flex: 8 },
    flexRow: { flexDirection: "row" },
    flexCol: { flexDirection: "column" },
    flexRowR: { flexDirection: "row-reverse" },
    flexColR: { flexDirection: "column-reverse" },

    flexWrap: { flexWrap: "wrap" },
    flexNowrap: { flexWrap: "nowrap" },

    justCenter: { justifyContent: "center" },
    justStart: { justifyContent: "flex-start" },
    justEnd: { justifyContent: "flex-end" },
    justBetween: { justifyContent: "space-between" },
    justAround: { justifyContent: "space-around" },
    justEvenly: { justifyContent: "space-evenly" },


    alignCenter: { alignItems: "center" },
    alignStart: { alignItems: "flex-start" },
    alignEnd: { alignItems: "flex-end" },
    alignBaseline: { alignItems: "baseline" },

    alignSelfCenter: { alignSelf: "center" },
    alignSelfStart: { alignSelf: "flex-start" },
    alignSelfEnd: { alignSelf: "flex-end" },



    /* Typograpxy*/
    h1: { fontSize: n(48) },
    h2: { fontSize: n(36) },
    h3: { fontSize: n(24) },
    h4: { fontSize: n(20) },
    h5: { fontSize: n(18) },
    title: { fontSize: n(16) },
    body: { fontSize: 10 },
    textCenter: { textAlign: "center" },
    textLeft: { textAlign: "left" },
    textRight: { textAlign: "right" },
    fontItalic: { fontStyle: "italic" },
    fontBold: { fontWeight: "bold" }
});

// const space = { p: padding", m: margin" };
// const length = [0, 1, 2, 3, 4, 5, 6, 7];
// const side = {
//     l: "Left",
//     r: "Right",
//     t: "Top",
//     b: "Bottom",
//     a: "",
//     v: "Vertical",
//     h: "Horizontal",
// };



// let d = Object.entries(space).reduce((st, [spK, spy]) => {
//     let dside = Object.entries(side).reduce((sid, [sdK, sdV]) => {
//         let et = length.reduce((t, el) => {
//             return { ...t, [`${spK}${sdK}${el}`]: { [`${spy}${sdV}`]: el } };
//         }, {});
//         return { ...sid, ...et };
//     }, {});
//     return { ...st, ...dside };
// }, {});
// console.log(JSON.stringify(d));
